apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupiter-base-ui
  labels:
    app: jupiter-base-ui
spec:
  {{ if not .Values.disabled }}
  replicas: 1
  {{ else }}
  replicas: 0
  {{ end }}
  selector:
    matchLabels:
      app: jupiter-base-ui
  template:
    metadata:
      labels:
        app: jupiter-base-ui
    spec:
      securityContext:
        fsGroup: 8001
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8}}
      volumes:
        - name: logs-volume
          emptyDir: {}
      containers:
        - name: jupiter-base-ui
          image: {{ .Values.image.id }}
          volumeMounts:
            - mountPath: {{ .Values.log.path }}
              name: logs-volume
          env:
            - name: VITE_AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: jupiter-auth0-credentials
                  key: domain
            - name: VITE_AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: jupiter-auth0-credentials
                  key: clientId
            - name: APP_LOGGING_LEVEL
              value: {{ .Values.log.apiLevel }}
            - name: ROOT_LOGGING_LEVEL
              value: {{ .Values.log.rootLevel }}
            - name: LOGS_PATH
              value: {{ .Values.log.path }}
            - name: IDP_PROVIDER
              value: {{ .Values.idp }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "35Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "1"
