{{- if .Values.useExternalSecret }}
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: jupiter-auth0-credentials
spec:
  backendType: secretsManager
  dataFrom:
    - usermanagement/auth0-credentials  
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: jupiter-auth0-credentials
type: Opaque
stringData:
  clientId: {{ .Values.oidc.uanalyzeNG.clientId }}
  domain: {{ .Values.auth0.domain }}
{{- end }}
