apiVersion: v1
kind: Service
metadata:
  name: jupiter-base-ui
  labels:
    {{- include "jupiter-base-ui.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: jupiter-base-ui
