---
name: Platform CI/CD
"on":
  push:
    branches-ignore:
      - 'dependabot/**'
  workflow_call:
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install dependency
        run: npm install
      - name: Run Lint
        run: npm run lint
  CI:
    uses: uniphore/platform-github-actions/.github/workflows/ci.yml@main
    secrets: inherit
    with:
      sonarqube-quality-gate: false
    needs: Lint
  CD:
    if: >
      github.event_name == 'push'
      && ! startsWith(github.event.head_commit.message, '[github-ci]')
      && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    needs: CI
    uses: uniphore/platform-github-actions/.github/workflows/cd.yml@main
    secrets: inherit
    with:
      images-map: ${{ needs.CI.outputs.images-map }}
